import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-blue-500">
          <div className="text-3xl font-bold underline">?기가 헤더</div>
          {children}
          <div>여기가 푸터</div>
        </div>
      </body>
    </html>
  );
}
